### ISSUE TITLE
client call service fail

### ISSUE THREAD

**Issue by leoterry-ulrica** [Cysharp/MagicOnion#107]
RpcException: Status(StatusCode=Unknown, Detail="MessagePack.Internal.MessagePackDynamicObjectResolverException: all public members must mark KeyAttribute or IgnoreMemberAttribute. type: Dist.Dme.Base.Common.Page.SimplePage`1[[Dist.Dme.Model.DTO.TaskRespDTO, Dist.Dme.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] member:LastPage
   at MessagePack.FormatterResolverExtensions.GetFormatterWithVerify[T](IFormatterResolver resolver)
   at MagicOnion.PriorityResolver.GetFormatter[T]()
   at MessagePack.FormatterResolverExtensions.GetFormatterWithVerify[T](IFormatterResolver resolver)
   at MessagePack.MessagePackSerializer.SerializeUnsafe[T](T obj, IFormatterResolver resolver)
   at MessagePack.LZ4MessagePackSerializer.SerializeCore[T](T obj, IFormatterResolver resolver)
   at MessagePack.LZ4MessagePackSerializer.Serialize[T](T obj, IFormatterResolver resolver)
   at MagicOnion.Server.MethodHandlerResultHelper.SerializeUnaryResult[T](UnaryResult`1 result, ServiceContext context)
   at MagicOnion.Server.MethodHandler.UnaryServerMethod[TRequest,TResponse](Byte[] request, ServerCallContext context)
")

**Comment by leoterry-ulrica** [comment]
Why do we add the tag KeyAttribute to every public attribute?
Feel a little redundant.

**Comment by neuecc** [comment]
use `MessagePack.Resolvers.ContractlessStandardResolver.Instance`, you can avoid to use attribute.
requires `KeyAttribute` in default is for performance reason.
ContractlessStandardResolver serialize to map({propertyname:value, propertyname:value...)
But `Key(int)` serialize to array([value, value, value...)

**Comment by leoterry-ulrica** [comment]
found a solution： [MessagePackObject(keyAsPropertyName: true)]
