### ISSUE TITLE
Swagger Breaks With Single-Parameter String Arguments

### ISSUE THREAD

**Issue by mwegner** [Cysharp/MagicOnion#122]
This will be easiest to show.  With a service function that takes a single string parameter, it shows up as "body" parameter type in Swagger, and breaks if you invoke:

![Screen Shot 2019-04-16 at 4 58 10 PM](https://user-images.githubusercontent.com/271924/56251617-16b05c00-6069-11e9-8256-16eea72e2464.png)

That full response body is:

```Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: a. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType) in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 658
   at Newtonsoft.Json.JsonTextReader.ReadAsString() in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 480
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter) in /_/Src/Newtonsoft.Json/JsonReader.cs:line 1219
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 149
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 828
   at MagicOnion.HttpGateway.MagicOnionHttpGatewayMiddleware.Invoke(HttpContext httpContext)
```

With multiple parameters, Swagger shows them as "formData" types, and correctly works:

![Screen Shot 2019-04-16 at 4 59 00 PM](https://user-images.githubusercontent.com/271924/56251687-4c554500-6069-11e9-8fd7-9db8dee942fe.png)

I didn't debug any further, since I need multiple parameters anyway--I was just testing early.  This might happen with other single-parameter invocations, not just string.

I guess Swagger expects the string to be posted as body text, and not multi-part form, and there's a way to flag single-parameter functions as "formData" instead of defaulting to body posts.  I've never integrated Swagger before, so unfortunately I can't help any further, but thought I would report this!

**Comment by CarlosAdmin** [comment]
#132 

1 in class  MagicOnion.HttpGateway.Swagger.SwaggerDefinitionBuilder line 178 add code 
                 `var` type = "formData";
                    if (parameterInfos.Length == 1)
                    {
                        var parameterType = parameterInfos[0].ParameterType;
                        if (!parameterType.IsValueType &&
                        parameterType != typeof(object) &&
                        parameterType != typeof(string))
                        {
                            type = "body";
                        }
                    }

                    return new Parameter
                    {
                        name = x.Name,
                        @in = type,
                        type = swaggerDataType,
                        description = parameterXmlComment,
                        required = !x.IsOptional,
                        @default = defaultObjectExample ?? ((x.IsOptional) ? defaultValue : null),
                        items = items,
                        @enum = enums,
                        collectionFormat = "multi",
                        schema = refSchema
                    };
`

2 in class  MagicOnion.HttpGateway.MagicOnionHttpGatewayMiddleware line 110 add code 
 deserializedObject = typeArgs.Count == 1 ?
                        args[0] : MagicOnionMarshallers.InsantiateDynamicArgumentTuple(typeArgs.ToArray(), args.ToArray());
3 build & test

**Comment by neuecc** [comment]
in `1.2.0`(now released), updates swaggerui. is it ok?
