### ISSUE TITLE
os-x64/moc does not work on mac os

### ISSUE THREAD

**Issue by JoeCoderJC** [Cysharp/MagicOnion#174]

**Comment by JoeCoderJC** [comment]
Project Compilation Start:/Users/mirabo_computer/Documents/UnityWorkspace/ProjectUnity/MagicOnionOculus/MagicOnionOculus.Client/Assets/../../Server/MagicOnionOculus.Server.csproj
Fail in batch running on Program.Run
System.AggregateException: One or more errors occurred. (One or more errors occurred. (No such file or directory)) (No such file or directory) ---> System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Buildalyzer.Environment.ProcessRunner.Start()
   at Buildalyzer.Environment.DotnetPathResolver.GetInfo(String projectPath, String dotnetExePath)
   at Buildalyzer.Environment.DotnetPathResolver.ResolvePath(String projectPath, String dotnetExePath)
   at Buildalyzer.Environment.EnvironmentFactory.CreateCoreEnvironment(EnvironmentOptions options)
   at Buildalyzer.Environment.EnvironmentFactory.GetBuildEnvironment(String targetFramework, EnvironmentOptions options)
   at Buildalyzer.ProjectAnalyzer.Build(String targetFramework, EnvironmentOptions environmentOptions)
   at MagicOnion.RoslynExtensions.<>c__DisplayClass3_0.<GetWorkspace>b__0(ProjectAnalyzer p) in /root/project/src/MagicOnion.UniversalCodeGenerator/Utils/RoslynExtensions.cs:line 83
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.WhereQueryOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at MagicOnion.RoslynExtensions.GetWorkspace(AnalyzerManager manager, EnvironmentOptions envOptions) in /root/project/src/MagicOnion.UniversalCodeGenerator/Utils/RoslynExtensions.cs:line 81
   at MagicOnion.RoslynExtensions.GetWorkspaceWithPreventBuildEvent(AnalyzerManager manager) in /root/project/src/MagicOnion.UniversalCodeGenerator/Utils/RoslynExtensions.cs:line 67
   at MagicOnion.RoslynExtensions.GetCompilationFromProject(String csprojPath, String[] preprocessorSymbols) in /root/project/src/MagicOnion.UniversalCodeGenerator/Utils/RoslynExtensions.cs:line 26
   at MagicOnion.CodeAnalysis.MethodCollector..ctor(String csProjPath, IEnumerable`1 conditinalSymbols) in /root/project/src/MagicOnion.UniversalCodeGenerator/CodeAnalysis/MethodCollector.cs:line 64
   at MagicOnion.CodeGenerator.Program.Run(String input, String output, Boolean unuseUnityAttr, String namespace, String[] conditionalSymbol) in /root/project/src/MagicOnion.UniversalCodeGenerator/Program.cs:line 40
---> (Inner Exception #0) System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Buildalyzer.Environment.ProcessRunner.Start()
   at Buildalyzer.Environment.DotnetPathResolver.GetInfo(String projectPath, String dotnetExePath)
   at Buildalyzer.Environment.DotnetPathResolver.ResolvePath(String projectPath, String dotnetExePath)
   at Buildalyzer.Environment.EnvironmentFactory.CreateCoreEnvironment(EnvironmentOptions options)
   at Buildalyzer.Environment.EnvironmentFactory.GetBuildEnvironment(String targetFramework, EnvironmentOptions options)
   at Buildalyzer.ProjectAnalyzer.Build(String targetFramework, EnvironmentOptions environmentOptions)
   at MagicOnion.RoslynExtensions.<>c__DisplayClass3_0.<GetWorkspace>b__0(ProjectAnalyzer p) in /root/project/src/MagicOnion.UniversalCodeGenerator/Utils/RoslynExtensions.cs:line 83
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---


UnityEngine.Debug:Log(Object)
<>c__DisplayClass1_0:<ExecuteMagicOnionCodeGenerator>b__0(Object, EventArgs) (at Assets/Editor/MenuItems.cs:55)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

**Comment by JoeCoderJC** [comment]
please help me! thanks

**Comment by neuecc** [comment]
Sorry, this is the common my generators issue.
Maybe here info is useful.
https://github.com/neuecc/MessagePack-CSharp/issues/355
https://github.com/neuecc/MessagePack-CSharp/issues/386
