### ISSUE TITLE
InvalidOperationException when closing Unity client with X button

### ISSUE THREAD

**Issue by LuigiElleBalotta** [Cysharp/MagicOnion#219]
Hello, when i close UnityClient with the X button i get this exception in the server console:

> Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Grpc.Core.Utils.GrpcPreconditions.CheckState(Boolean condition)
   at Grpc.Core.Internal.AsyncCallServer2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable1 optionalWrite)
   at Grpc.Core.Internal.DuplexStreamingServerCallHandler2.HandleCall(ServerRpcNew newRpc, CompletionQueueSafeHandle cq)
   at Grpc.Core.Server.HandleCallAsync(ServerRpcNew newRpc, CompletionQueueSafeHandle cq, Action2 continuation)

and this in unity client (COMPILED): 
RpcException: Status(StatusCode=Unavailable, Detail="failed to connect to all addresses")

There is another case:
with a non compiled client (so playing inside unity), if i click the button to stop the debug, the client stops fine, the server has no error, but if i don't restart the server and RESTART the unity debug, the debug session won't start.
You can test with my repo: https://github.com/LuigiElleBalotta/ElleRealTime

**Comment by marekhanzlik** [comment]
Inside unity code, where you create your StreamingHubClient add this method
```
protected async override void OnDestroy()
{
    await client.DisposeAsync();
}
```
unity call this method automaticaly when destroying the script

**Comment by LuigiElleBalotta** [comment]
Here? https://github.com/LuigiElleBalotta/ElleRealTime/blob/master/MagicOnionTest/Assets/Scripts/InitClient.cs

**Comment by LuigiElleBalotta** [comment]
Works like a charm!!! Some1 should write this in the readme.md!!

**Comment by marekhanzlik** [comment]
With the console client the solution is not so straightforward, you need to capture the exit signal of the application and react on it before application close.
I do it this way:
Create CancelationToken,
pass it to hubs and register to cancelationToken ```cancelationToken.Register(() => client.DisposeAsync())```
I register to CTRL+C / Close events with ```AppDomain.CurrentDomain.ProcessExit += delegate { ShutDown(); };```
the ShutDown method calls cancelationToken.Cancel()

this `should` dispose before the close (this is distilation of my code so i hope it'll work for you)

**Comment by LuigiElleBalotta** [comment]
i'll give a look to your code if it's public!

**Comment by marekhanzlik** [comment]
> Works like a charm!!! Some1 should write this in the readme.md!!

Well it's mentioned there (in streaming hub fundamentals) but i agree its done there in not so intuitive way (and it's not mentioned with the OnDestroy context)

**Comment by marekhanzlik** [comment]
https://github.com/marekhanzlik/MagicOnionClientDisposeStub

**Comment by marekhanzlik** [comment]
And could you please close this issue? thanks

**Comment by qq60665** [comment]
> https://github.com/marekhanzlik/MagicOnionClientDisposeStub

thank you every much.
