### ISSUE TITLE
Dependency injection of a MagicOnion.Client ?

### ISSUE THREAD

**Issue by christopheblin** [Cysharp/MagicOnion#225]
In the documentation, there is an example of Dependency Injection with IOptions and ILogger.

However, I do not find how to inject an interface created via  MagicOnionClient.Create

    public interface IMyFirstService : IService<IMyFirstService>
    {
        UnaryResult<int> Sum(int x, int y);
    }

    public abstract class MyFirstServiceClientFactory
    {
        public static IMyFirstService Build()
        {
            return MagicOnionClient.Create<IMyFirstService>(new Channel("localhost", 12301, ChannelCredentials.Insecure));
        }
    }

    public interface IMySecondService : IService<IMySecondService>
    {
        UnaryResult<int> Multiply(int x, int y);
    }

    class MySecondService : ServiceBase<IMySecondService>, IMySecondService
    {
        private IMyFirstService adder;

        public MySecondService(IMyFirstService adder)
        {
            this.adder = adder;
        }

        public async UnaryResult<int> Multiply(int x, int y)
        {
            Logger.Debug($"Received Multiply: {r.x}, {r.y}");
            //imagine that we use adder to do the multiplication for example purposes
        }
    }

    class Program
    {
        static async Task Main(string[] args)
        {
            GrpcEnvironment.SetLogger(new Grpc.Core.Logging.ConsoleLogger());

            await MagicOnionHost.CreateDefaultBuilder()
                .ConfigureHostConfiguration(configHost =>
                {
                    configHost.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
                })
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddSingleton(MyFirstServiceClientFactory.Build());
                    services.AddSingleton<IMySecondService, MySecondService>();
                })
                .UseMagicOnion()
                .RunConsoleAsync();
        }
    }

I got the exception GenericArguments[0], 'MagicOnion.Client.DynamicClient.Service1Def.IMyFirstServiceClient', on 'TServiceBase CreateService[TServiceBase,TServiceInterface](MagicOnion.Server.ServiceContext)' violates the constraint of type 'TServiceBase'.

I suppose this is because MagicOnionServer tries to build a server for IMyFirstService because of the IService<IMyfirstService> marker.

However, I can not remove the marker because then it throws a compile error to build the client (i.e IMyFirstService is not a IService so I can not use Crete method)

So how do you share the code between a client and a server when the client is also a server ?

Full exception

```
System.ArgumentException
  HResult=0x80070057
  Message=GenericArguments[0], 'MagicOnion.Client.DynamicClient.Service1Def.IMyFirstServiceClient', on 'TServiceBase CreateService[TServiceBase,TServiceInterface](MagicOnion.Server.ServiceContext)' violates the constraint of type 'TServiceBase'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at MagicOnion.Server.MethodHandler..ctor(MagicOnionOptions options, Type classType, MethodInfo methodInfo, String methodName)
   at MagicOnion.Server.MagicOnionEngine.<>c__DisplayClass3_0.<BuildServerServiceDefinition>b__3(Type classType)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass32_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(IEnumerable`1 targetTypes, MagicOnionOptions option)
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(Assembly[] searchAssemblies, MagicOnionOptions option)
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(MagicOnionOptions options)
   at MagicOnion.Hosting.MagicOnionServerServiceExtensions.<>c__DisplayClass8_0.<AddMagicOnionHostedServiceDefinition>b__1(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(IServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)
   at MagicOnion.Hosting.MagicOnionServerServiceExtensions.<>c__DisplayClass6_0.<UseMagicOnion>b__1(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(IServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Service2.Program.<Main>d__0.MoveNext() in xxx\Service2\Program.cs:line 20

Inner Exception 1:
VerificationException: Method MagicOnion.Server.ServiceLocatorHelper.CreateService: type argument 'MagicOnion.Client.DynamicClient.Service1Def.IMyFirstServiceClient' violates the constraint of type parameter 'TServiceBase'.
```

**Comment by christopheblin** [comment]
I hope my question is clear, I've setup a small project on github to demonstrate: https://github.com/christopheblin/MagicOnionExample

**Comment by mayuki** [comment]
Thank you for reporting.

At first, `MagicOnionClient.Create<T>` dynamically generates assembly for service proxies. Second, `MagicOnionEngine.BuildServerServiceDefinition` collects services from all assembly.

As a result, `MagicOnionEngine` finds types implementing `IService<T>` in dynamic-generated assemblies. `MagicOnionEngine` treats the service client-proxies as a server-service implementation. So, registration fails, and the exception is thrown.

## Workaround
Register service as a factory.
```csharp
services.AddSingleton(_ => MyFirstServiceClientFactory.Build());
```

or

Explicity specify server-service implementation types or assemblies on start-up.
```csharp
.UseMagicOnion(types: new [] { typeof(MySecondService) })
```

**Comment by christopheblin** [comment]
Thank you for providing a workaround.

In the end, I am using `.UseMagicOnion(types: typeof(Program).Assembly.GetTypes())` so that I do not need to manually register services one by one but it also prevent MagicOnion for looking into the dynamically generated assemblies
