### ISSUE TITLE
Raised exception when using RedisGroupRepositoryFactory

### ISSUE THREAD

**Issue by ksksni** [Cysharp/MagicOnion#373]
When I using `[GroupConfiguration(typeof(RedisGroupRepositoryFactory))]` attribute, `System.MissingMethodException` was raised.
Version: 4.0.1

```
System.MissingMethodException
  HResult=0x80131513
  Message=No parameterless constructor defined for type 'MagicOnion.Server.Redis.RedisGroupRepositoryFactory'.
  Source=System.Private.CoreLib
  スタック トレース:
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(IServiceProvider serviceProvider, IEnumerable`1 targetTypes, MagicOnionOptions options)
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(IServiceProvider serviceProvider, Assembly[] searchAssemblies, MagicOnionOptions options)
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(IServiceProvider serviceProvider, MagicOnionOptions options)
   at Microsoft.Extensions.DependencyInjection.MagicOnionServicesExtensions.<>c__DisplayClass0_0.<AddMagicOnion>b__0(IServiceProvider sp)
   ...
```

**Comment by mayuki** [comment]
Thank you for your report. We've fixed the issue and released version 4.0.2.
