### ISSUE TITLE
TypeLoadException in MagicOnion.OpenTelemetry with opentelemetry-1.0.0-rc1.1

### ISSUE THREAD

**Issue by itn3000** [Cysharp/MagicOnion#380]
# Overview

TypeLoadException occured when using MagicOnion.OpenTelemetry with latest opentelemetry package.
This is because OpenTelemetry's API changes.

# Environment

* dotnet-sdk: 5.0.0
* MagicOnion.OpenTelemetry: 3.0.13
* OpenTelemetry: 1.0.0-rc1.1

# Steps to reproduce

* create new project
* add MagicOnion.OpenTelemetry-3.0.13 nuget package
* add OpenTelemetry-1.0.0-rc1.1 nuget package
* run following code

```csharp
using Microsoft.Extensions.DependencyInjection;
using MagicOnion.OpenTelemetry;
using Microsoft.Extensions.Configuration;

namespace magiconiontest
{
    class Program
    {
        static void Main(string[] args)
        {
            var config = new ConfigurationBuilder().Build();
            new ServiceCollection()
                .AddSingleton<IConfiguration>(provider => config)
                .AddMagicOnionOpenTelemetry()
                ;
        }
    }
}
```

# Expected Behavior

exit with code 0 and no output

# Actual Behavior

following exception was out.

```
Unhandled exception. System.TypeLoadException: Could not load type 'OpenTelemetry.Trace.Configuration.TracerBuilder' from assembly 'OpenTelemetry, Version=1.0.0.1, Culture=neutral, PublicKeyToken=7bd6737fe5b67e3c'.
   at MagicOnion.OpenTelemetry.OpenTelemetryServiceCollectionExtensions.AddMagicOnionOpenTelemetry
   at MagicOnion.OpenTelemetry.OpenTelemetryServiceCollectionExtensions.AddMagicOnionOpenTelemetry(IServiceCollection services, MagicOnionOpenTelemetryOptions options)
   at MagicOnion.OpenTelemetry.OpenTelemetryServiceCollectionExtensions.AddMagicOnionOpenTelemetry(IServiceCollection services, String configurationName)
   at magiconiontest.Program.Main(String[] args) in D:\src\gitrepos\dotnet-sandbox\magiconiontest\Program.cs:line 16
```

**Comment by itn3000** [comment]
oh, I found MagicOnion.OpenTelemetry is deprecated package, I close this issue.

**Comment by neuecc** [comment]
OpenTelemetry package will publish `MagicOnion.Server.OpenTelemetry` after #374 merged.
