### ISSUE TITLE
Swagger integration is not working by steps on README.md

### ISSUE THREAD

**Issue by ktanakaj** [Cysharp/MagicOnion#392]
I created MagicOnion 4.0.3 server with Swagger integration on .NET5.
But I can't use Swagger by steps on README.md. I guess there are undocumented knowledge.

First, I created MagicOnion project as Visual Studio C# gRPC project.
This project can't be accessed swagger page because default protocol on appsettings.json is `Http2`.
I guess Swagger page need `Http1AndHttp2`.

Second, Swagger can't access `GrpcChannel.ForAddress("https://localhost:5001")` because development certificate is not unsecure. I disabled certificate validation.
```
        private static HttpClient MakeUnsafeHttpClient()
        {
            var httpClientHandler = new HttpClientHandler();
            httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
            return new HttpClient(httpClientHandler);
        }
```
```
GrpcChannel.ForAddress("https://localhost:5001", new GrpcChannelOptions { HttpClient = SharedConfiguration.MakeUnsafeHttpClient() }
```

And also, I think other solution that `GrpcChannel.ForAddress("http://localhost:5000")`, but it is not working because PROTOCOL_ERROR occurred. I guess many developers want to use this solution instead certificate validation disabling. If you know the solution, can you add it to README.md too?
```
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. Http2ConnectionException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.Net.Http.Http2ConnectionException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).
   at System.Net.Http.Http2Connection.ThrowProtocolError(Http2ProtocolErrorCode errorCode)
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request, CancellationToken cancellationToken, Boolean mustFlush)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at MagicOnion.Server.HttpGateway.MagicOnionHttpGatewayMiddleware.Invoke(HttpContext httpContext)
```

**Comment by ktanakaj** [comment]
> And also, I think other solution that `GrpcChannel.ForAddress("http://localhost:5000")`, but it is not working because PROTOCOL_ERROR occurred. 

I found the solution. The endpoints will be separated for Http2 as gRPC and Http1 as Swagger, and also Swagger URL will be `http://localhost:5001/swagger/`.

```
Kestrel:
  Endpoints:
    Grpc:
      Url: http://localhost:5000
      Protocols: Http2
    Http:
      Url: http://localhost:5001
      Protocols: Http1
```

**Comment by ktanakaj** [comment]
FYI. I wrote my blog to explain this problem and solution now.
http://honeplus.blog50.fc2.com/blog-entry-224.html
