### ISSUE TITLE
Cannot create swagger definition when using StringCollection

### ISSUE THREAD

**Issue by mv00** [Cysharp/MagicOnion#396]
We are unable to use the swagger integration when we have StringCollection in our service. I've included a small service which results in the error.

` using MagicOnion;
using MagicOnion.Server;
using System;
using System.Collections.Specialized;
#pragma warning disable CS1998

namespace GrpcService.Services
{
    public interface ILabService : IService<ILabService>
    {
        UnaryResult<StringCollection> StringCollection(StringCollection stringCollection);
    }

    public class LabService : ServiceBase<ILabService>, ILabService
    {
        public async UnaryResult<StringCollection> StringCollection(StringCollection stringCollection)
        {
            return stringCollection;
        }
    }
}
`

`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Collections.Specialized
  StackTrace:
   at System.Collections.Specialized.StringCollection.System.Collections.IEnumerable.GetEnumerator()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonConverter[] converters)
   at MagicOnion.Server.HttpGateway.Swagger.SwaggerDefinitionBuilder.<>c__DisplayClass6_0.<BuildParameters>b__0(ParameterInfo x) in C:\src\laboration\MagicOnion-master\src\MagicOnion.Server.HttpGateway\Swagger\SwaggerDefinitionBuilder.cs:line 175

  This exception was originally thrown at this call stack:
    [External Code]
    MagicOnion.Server.HttpGateway.Swagger.SwaggerDefinitionBuilder.BuildParameters.AnonymousMethod__0(System.Reflection.ParameterInfo) in SwaggerDefinitionBuilder.cs`

**Comment by neuecc** [comment]
Please use `List<string>`.

**Comment by mv00** [comment]
Alright, we will try to migrate legacy code to List<string>. Thanks!
