### ISSUE TITLE
RpcException: Status(StatusCode="Unimplemented", Detail="Service is unimplemented.") when implementation in separate class library (.NET5)

### ISSUE THREAD

**Issue by YaroslavHalai** [Cysharp/MagicOnion#418]
Hi, 

I implemented the server as three net5.0 projects.
1) ASP.NET Core gRPC web application project (**WebApplication**).
2) net5.0 class library with interfaces (**Extensibility**).
3) net5.0 class library with implementations of the interfaces (**Service**).

I referenced the 2nd project in the 3rd and referenced the 3rd project in the 1st (**WebApplication (has reference to)->  Service (has reference to)-> Extensibility**).
So, the gRPC web application project has reference to the dll with the service implementation.

When I move the service implementation directly to the WebApplication everything works fine.

Why am I getting the following error? Please, help me out.
**RpcException: Status(StatusCode="Unimplemented", Detail="Service is unimplemented.")**

**Comment by mayuki** [comment]
Please make sure that MagicOnion has registered your service correctly.
You can see ASP.NET Core (gRPC-dotnet) logs by adding the following setting to appsettings.json

```json
{
    "Logging": {
        "LogLevel": {
            "Default": "Trace",
            "System": "Information",
            "Microsoft": "Information"
        }
    }
}
```

```
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[2]
      Discovering gRPC methods for MagicOnion.Server.Glue.MagicOnionGlueService`1[MagicOnionGlue].
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
      Added gRPC method 'SignInAsync' to service 'IAccountService'. Method type: 'Unary', route pattern: '/IAccountService/SignInAsync'.
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
      Added gRPC method 'GetCurrentUserNameAsync' to service 'IAccountService'. Method type: 'Unary', route pattern: '/IAccountService/GetCurrentUserNameAsync'.
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
      Added gRPC method 'DangerousOperationAsync' to service 'IAccountService'. Method type: 'Unary', route pattern: '/IAccountService/DangerousOperationAsync'.
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
      Added gRPC method 'HelloAsync' to service 'IGreeterService'. Method type: 'Unary', route pattern: '/IGreeterService/HelloAsync'.
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
      Added gRPC method 'Connect' to service 'ITimerHub'. Method type: 'DuplexStreaming', route pattern: '/ITimerHub/Connect'.
```

**Comment by YaroslavHalai** [comment]
And... Does MagicOnion support generic services? I've tried to create such a service and got exception:

System.InvalidOperationException: Can't create handler. Path:ICommandTransmitter/Transmit
 ---> System.ArgumentException: Type CommandRouter.ClientModule.Extensibility.Commands.PeripheralCommand`2[TCommand,TParameter] contains generic parameters (Parameter 'type')
   at System.Dynamic.Utils.TypeUtils.ValidateType(Type type, String paramName, Int32 index)
   at System.Dynamic.Utils.TypeUtils.ValidateType(Type type, String paramName, Boolean allowByRef, Boolean allowPointer)
   at System.Linq.Expressions.Expression.Validate(Type type, Boolean allowByRef)
   at System.Linq.Expressions.Expression.Parameter(Type type, String name)
   at MagicOnion.Server.MethodHandler..ctor(Type classType, MethodInfo methodInfo, String methodName, MethodHandlerOptions handlerOptions, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at MagicOnion.Server.MethodHandler..ctor(Type classType, MethodInfo methodInfo, String methodName, MethodHandlerOptions handlerOptions, IServiceProvider serviceProvider)
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(IServiceProvider serviceProvider, IEnumerable`1 targetTypes, MagicOnionOptions options)
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(IServiceProvider serviceProvider, Assembly[] searchAssemblies, MagicOnionOptions options)
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(IServiceProvider serviceProvider, MagicOnionOptions options)
   at Microsoft.Extensions.DependencyInjection.MagicOnionServicesExtensions.<>c__DisplayClass0_0.<AddMagicOnion>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.MagicOnionServicesExtensions.<>c__DisplayClass3_0.<AddMagicOnionCore>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.MagicOnionEndpointRouteBuilderExtensions.MapMagicOnionService(IEndpointRouteBuilder builder)
   at CommandRouter.WebApp.Startup.<>c.<Configure>b__1_0(IEndpointRouteBuilder endpoints) in D:\Projects\CommandRouter\CommandRouter.WebApp\Startup.cs:line 21
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at CommandRouter.WebApp.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in D:\Projects\CommandRouter\CommandRouter.WebApp\Startup.cs:line 19
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.MethodInfoExtensions.InvokeWithoutWrappingExceptions(MethodInfo methodInfo, Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at CommandRouter.WebApp.Program.Main(String[] args) in D:\Projects\CommandRouter\CommandRouter.WebApp\Program.cs:line 15

**Comment by YaroslavHalai** [comment]
And the third issue, why MessagePack can't resolve the value? Is MagicOnion designed to transmit only primitive types?

![image](https://user-images.githubusercontent.com/79108019/113276636-b0ba4f00-92e8-11eb-90d9-f04fbb91a672.png)

**Comment by mayuki** [comment]
MagicOnion relies on MessagePack for the serialization process, it needs to be configured to allow MessagePack to serialize it.
Is the class you want to send marked with `MessagePackObject` attribute?

https://github.com/neuecc/MessagePack-CSharp#quick-start

**Comment by YaroslavHalai** [comment]
No, it doesn't. I'll try to mark it.

The next issue, is MagicOnion support method overloads in services?

System.InvalidOperationException: Method does not allow overload, CommandTransmitter.Transmit

**Comment by mayuki** [comment]
MagicOnion does not support overloading (and there are no plans to do so at this time).
The workaround is to separate the methods or use [MessagePack's Union](https://github.com/neuecc/MessagePack-CSharp#union).

**Comment by YaroslavHalai** [comment]
@mayuki Thank you, marking with MessagePackObject worked.

**Comment by YaroslavHalai** [comment]
@mayuki do you have any updates about the issue when I put service implementation into the separate class library and reference this library in my ASP.NET Core project?
