### ISSUE TITLE
MessagePack.MessagePackSerializationException: Failed to deserialize System.Int32[] value.

### ISSUE THREAD

**Issue by ekrn** [Cysharp/MagicOnion#455]
If the server-side provides data which is array of int32 (length > 60) the error got as follows~  So what is the reason, i can not find the reason and resolutions, pls help me~

System.AggregateException: One or more errors occurred. (Failed to deserialize System.Int32[] value.)
 ---> MessagePack.MessagePackSerializationException: Failed to deserialize System.Int32[] value.
 ---> MessagePack.MessagePackSerializationException: Unexpected msgpack code 201 (ext 32) encountered.
   at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.ReadArrayHeader()
   at MessagePack.Formatters.Int32ArrayFormatter.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](ReadOnlyMemory`1 buffer, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at MagicOnion.Client.ResponseContext`1.Deserialize()
   at MagicOnion.UnaryResult`1.UnwrapResponse()
   --- End of inner exception stack trace ---

**Comment by mayuki** [comment]
We could not reproduce it. Could you provide us with reproducible code, method signatures, response types, etc.?
