### ISSUE TITLE
`MethodHandler()` constructor throws an uncaught exception during `MapMagicOnionService()`

### ISSUE THREAD

**Issue by dahlia** [Cysharp/MagicOnion#529]
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at MagicOnion.Server.MethodHandler..ctor(Type classType, MethodInfo methodInfo, String methodName, MethodHandlerOptions handlerOptions, IServ
iceProvider serviceProvider)
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(IServiceProvider serviceProvider, IEnumerable`1 targetTypes, MagicOnionOpt
ions options)
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(IServiceProvider serviceProvider, Assembly[] searchAssemblies, MagicOnionO
ptions options)
   at MagicOnion.Server.MagicOnionEngine.BuildServerServiceDefinition(IServiceProvider serviceProvider, MagicOnionOptions options)
   at Microsoft.Extensions.DependencyInjection.MagicOnionServicesExtensions.<>c__DisplayClass0_0.<AddMagicOnion>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverCon
text context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScop
e scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScop
e)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.MagicOnionServicesExtensions.<>c__DisplayClass3_0.<AddMagicOnionCore>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverCon
text context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScop
e scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScop
e)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.MagicOnionEndpointRouteBuilderExtensions.MapMagicOnionService(IEndpointRouteBuilder builder)
   at NineChronicles.Headless.GraphQLService.GraphQLStartup.<>c__DisplayClass5_0.<Configure>b__0(IEndpointRouteBuilder endpoints) in C:\Users\se
ungmin\planetarium\9c-launcher\NineChronicles.Headless\NineChronicles.Headless\GraphQLService.cs:line 165
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at NineChronicles.Headless.GraphQLService.GraphQLStartup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\seungmin\pla
netarium\9c-launcher\NineChronicles.Headless\NineChronicles.Headless\GraphQLService.cs:line 160
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplic
ationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at NineChronicles.Headless.Executable.Program.Run(String appProtocolVersionToken, String genesisBlockPath, Boolean noMiner, String host, Null
able`1 port, String swarmPrivateKeyString, String minerPrivateKeyString, String storeType, String storePath, String[] iceServerStrings, String[]
 peerStrings, String[] trustedAppProtocolVersionSigners, Boolean rpcServer, String rpcListenHost, Nullable`1 rpcListenPort, Boolean graphQLServe
r, String graphQLHost, Nullable`1 graphQLPort, String graphQLSecretTokenPath, Boolean noCors, Int32 workers, Int32 confirmations, Boolean nonblo
ckRenderer, Int32 nonblockRendererQueue, Boolean strictRendering, NetworkType networkType, Boolean isDev, Int32 blockInterval, Int32 reorgInterv
al, Boolean logActionRenders, String awsCognitoIdentity, String awsAccessKey, String awsSecretKey, String awsRegion, Int32 txLifeTime, Int32 mes
sageTimeout, Int32 tipTimeout, Int32 demandBuffer, String[] staticPeerStrings, Int32 minerCount, Boolean skipPreload, Int32 minimumBroadcastTarg
et, Int32 bucketSize, String chainTipStaleBehaviorType, Int32 txQuotaPerSigner, Boolean rpcRemoteServer, Boolean rpcHttpServer, Int32 maximumPol
lPeers, String transportType, Nullable`1 cancellationToken) in C:\Users\seungmin\planetarium\9c-launcher\NineChronicles.Headless\NineChronicles.
Headless.Executable\Program.cs:line 372
```

I tried to figure it out by attaching debugger, but unfortunately I couldn't find enough clue.  Here's some debugging information inside [`MapMagicOnionService()` constructor][1]:

![](https://user-images.githubusercontent.com/12431/177923199-d47f3e4b-3ebb-485e-9146-4aadad21231d.png)

Note that the expression I evaluated in the above debugger session was:

```csharp
classType.GetInterfaces().Select(x =>
  (
    x,
    x.GetTypeInfo().IsGenericType,
    x.GetTypeInfo().IsGenericType
      ? x.GetGenericTypeDefinition()
      : null
  )
)
```

Please see also generated source files: <https://gist.github.com/boscohyun/cf325c35def7399e3a60e2ad86d63df9>.

Our source code invoking `MapMagicOnionService()`: <https://github.com/planetarium/NineChronicles.Headless/blob/73925745e2b8eacad190bba55d553a8c831d288e/NineChronicles.Headless/GraphQLService.cs#L165>.

The produced environment:

- Windows 11
- .NET 6.0.202
- MessagePack-CSharp 2.4.35
- MagicOnion 4.5.1

[1]: https://github.com/Cysharp/MagicOnion/blob/4.5.1/src/MagicOnion.Server/MethodHandler.cs#L58

**Comment by mayuki** [comment]
Sorry for the late reply.

This was due to the generated client nested classes being incorrectly picked up as service implementations.
https://gist.github.com/boscohyun/cf325c35def7399e3a60e2ad86d63df9#file-magiconion-generated-cs-L558

We will fix the generated code to mark it as `Ignore`, but in a future version we will only treat `public` services as service implementations.
