### ISSUE TITLE
client dit not work on net core 2.1

### ISSUE THREAD

**Issue by jovi-Li** [Cysharp/MagicOnion#536]
it is fine when use net 6.0 ,change framwork to net core 2.1  and rebuild ,got error ：Grpc.Core.RpcException:“Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The server returned an invalid or unrecognized response.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Web.GrpcWebHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Grpc.Net.Client.Web/GrpcWebHandler.cs:line 166
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout) in /_/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 481")”

code like ：
var channel = GrpcChannel.ForAddress(testurl, new GrpcChannelOptions
            {
                HttpHandler = new GrpcWebHandler(new HttpClientHandler())
            });
var server = MagicOnionClient.Create<IGrpcOrderService>(channel);
var  data = await server.test0();

**Comment by mayuki** [comment]
.NET Core 2.1 is already officially unsupported and we do not support it either.

But in general, if gRPC works, MagicOnion should also work. 
Try to make sure it works with NET Core 2.1 and plain gRPC. (We do not plan to support .NET Core 2.1)

**Comment by jovi-Li** [comment]
I test my netcore2.1 client  project with Grpc.Net.Client and  Grpc.Net.Client.Web  and server net5.0 with Grpc.AspNetCore.Web ,it is works well .

**Comment by jovi-Li** [comment]
I intedn to use migiconion to replace my old project's rpc function which it hard to upgrade

**Comment by jovi-Li** [comment]
I intedn to use migiconion to replace my old project's rpc function which it hard to upgrade

**Comment by jovi-Li** [comment]
I rebuild MagicOnion.Client use Grpc.Net.Client(2.48.0) with netstand2.0  locally,and the demo works fine
