### ISSUE TITLE
Unity StreamingHub issue when using BestHTTP 2 implementation

### ISSUE THREAD

**Issue by FreshL4ma** [Cysharp/MagicOnion#601]
I am using the following package: [doctorseus/grpc-dotnet-unity](https://github.com/doctorseus/grpc-dotnet-unity) in conjunction with BestHTTP 2. UnaryCalls are working as expected, but the following issue arises when establishing connection with the StreamingHub.

On the Client-Side:
```
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="The request started successfully (StatusCode = OK), but the StreamingHub client has failed to negotiate with the server.")
  at MagicOnion.Client.StreamingHubClientBase`2[TStreamingHub,TReceiver].__ConnectAndSubscribeAsync (TReceiver receiver, System.Threading.CancellationToken cancellationToken) [0x0031a] in [MyProject]\Assets\Scripts\MagicOnion\MagicOnion.Client\StreamingHubClientBase.cs:106 
```

On the Server-Side the following error is given:
```
Grpc.AspNetCore.Server.ServerCallHandler[14]
      Error reading message.
      System.IO.IOException: The request stream was aborted.
       ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
         --- End of inner exception stack trace ---
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken)
```

Here are the logs from Best HTTP2:
```
{"tid":1,"div":"RequestEventHelper","msg":"Enqueue request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: StateChange, State: Queued]","stack":"  at Core.RequestEventHelper.EnqueueRequestEvent (Core.RequestEventInfo event) [0x00012] 

{"tid":1,"div":"RequestEventHelper","msg":"Enqueue request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: Resend]","stack":"  at Core.RequestEventHelper.EnqueueRequestEvent (Core.RequestEventInfo event) [0x00012]

{"tid":1,"div":"RequestEventHelper","msg":"Processing request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: StateChange, State: Queued]","stack":"  at Core.RequestEventHelper.ProcessQueue () [0x0001f] 

{"tid":1,"div":"RequestEventHelper","msg":"Processing request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: Resend]","stack":"  at Core.RequestEventHelper.ProcessQueue () [0x0001f] 

{"tid":1,"div":"ProxyDetector","msg":"OnRequestEvent(RequestEvents.Resend) uri: 'https:\/\/localhost:5001\/IChatHub\/Connect'","stack":"  at Proxies.Autodetect.ProxyDetector.OnRequestEvent (Core.RequestEventInfo event) [0x0002f] 

{"tid":1,"div":"ProxyDetector","msg":"Calling ProgrammaticallyAddedProxyDetector's GetProxy","stack":"  at Proxies.Autodetect.ProxyDetector.OnRequestEvent (Core.RequestEventInfo event) [0x00090] 

{"tid":1,"div":"ProxyDetector","msg":"Calling EnvironmentProxyDetector's GetProxy","stack":"  at Proxies.Autodetect.ProxyDetector.OnRequestEvent (Core.RequestEventInfo event) [0x00090]

{"tid":1,"div":"EnvironmentProxyDetector","msg":"GetProxy - HTTPS_PROXY: ''","stack":"  at Proxies.Autodetect.EnvironmentProxyDetector.Proxies.Autodetect.IProxyDetector.GetProxy (HTTPRequest request) [0x0003a]

{"tid":1,"div":"ProxyDetector","msg":"Calling FrameworkProxyDetector's GetProxy","stack":"  at Proxies.Autodetect.ProxyDetector.OnRequestEvent (Core.RequestEventInfo event) [0x00090] 

{"tid":1,"div":"ProxyDetector","msg":"No Proxy for 'https:\/\/localhost:5001\/IChatHub\/Connect'.","stack":"  at Proxies.Autodetect.ProxyDetector.OnRequestEvent (Core.RequestEventInfo event) [0x001bd]

{"tid":1,"div":"RequestEventHelper","msg":"Enqueue request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: StateChange, State: Initial]","stack":"  at Core.RequestEventHelper.EnqueueRequestEvent (Core.RequestEventInfo event) [0x00012] 

{"tid":1,"div":"HostConnection","msg":"GetNextAvailable - returning with connection. state: Processing, CanProcessMultiple: True","stack":"  at Core.HostConnection.GetNextAvailable (HTTPRequest request) [0x0008c] 

{"tid":1,"div":"RequestEventHelper","msg":"Enqueue request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: StateChange, State: Processing]","stack":"  at Core.RequestEventHelper.EnqueueRequestEvent (Core.RequestEventInfo event) [0x00012] 

{"tid":1,"div":"HTTP2Handler","msg":"Process request called","stack":"  at Connections.HTTP2.HTTP2Handler.Process (HTTPRequest request) [0x00001]

{"tid":1,"div":"RequestEventHelper","msg":"Processing request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: StateChange, State: Initial]","stack":"  at Core.RequestEventHelper.ProcessQueue () [0x0001f] 

{"tid":1,"div":"RequestEventHelper","msg":"Processing request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: StateChange, State: Processing]","stack":"  at Core.RequestEventHelper.ProcessQueue () [0x0001f]

{"tid":690,"div":"RequestEventHelper","msg":"Enqueue request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: TimingData, Name: Queued, Time: 30.12.2022 15:12:51]","stack":"  at Core.RequestEventHelper.EnqueueRequestEvent (Core.RequestEventInfo event) [0x00012] 

{"tid":690,"div":"HTTP2Stream","msg":"[13] Request assigned to stream. Remote Window: 98.304. Uri: https:\/\/localhost:5001\/IChatHub\/Connect","stack":"  at Connections.HTTP2.HTTP2Stream.Assign (HTTPRequest request) [0x0002f]

{"tid":690,"div":"HPACKEncoder","msg":"[13] - Encode - Header(1\/1): 'user-agent': 'grpc-dotnet\/2.50.0 (Mono 6.13.0; CLR 4.0.30319.42000; netstandard2.1; windows; x64)'","stack":"  at Connections.HTTP2.HPACKEncoder+<>c__DisplayClass5_1.<Encode>b__0 (System.String header, System.Collections.Generic.List`1[T] values) [0x000c5]

{"tid":690,"div":"HPACKEncoder","msg":"[13] - Encode - Header(1\/1): 'grpc-accept-encoding': 'identity,gzip'","stack":"  at Connections.HTTP2.HPACKEncoder+<>c__DisplayClass5_1.<Encode>b__0 (System.String header, System.Collections.Generic.List`1[T] values) [0x000c5]

{"tid":690,"div":"HPACKEncoder","msg":"[13] - Encode - Header(1\/1): 'authorization': 'Bearer here-is-my-encoded-token'","stack":"  at Connections.HTTP2.HPACKEncoder+<>c__DisplayClass5_1.<Encode>b__0 (System.String header, System.Collections.Generic.List`1[T] values) [0x000c5]

{"tid":690,"div":"HPACKEncoder","msg":"[13] - Encode - Header(1\/1): 'content-type': 'application\/grpc'","stack":"  at Connections.HTTP2.HPACKEncoder+<>c__DisplayClass5_1.<Encode>b__0 (System.String header, System.Collections.Generic.List`1[T] values) [0x000c5]

{"tid":1,"div":"RequestEventHelper","msg":"Processing request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: TimingData, Name: Queued, Time: 30.12.2022 15:12:51]","stack":"  at Core.RequestEventHelper.ProcessQueue () [0x0001f]

{"tid":690,"div":"HPACKEncoder","msg":"[13] - Encode - Header(1\/1): 'accept-encoding': 'gzip, br, identity'","stack":"  at Connections.HTTP2.HPACKEncoder+<>c__DisplayClass5_1.<Encode>b__0 (System.String header, System.Collections.Generic.List`1[T] values) [0x000c5] 

{"tid":690,"div":"HTTP2Stream","msg":"[13] State changed from Idle to Open","stack":"  at Connections.HTTP2.HTTP2Stream.set_State (Connections.HTTP2.HTTP2StreamStates value) [0x00020]

{"tid":690,"div":"HTTP2Handler","msg":"Sending frame: [HTTP2FrameHeaderAndPayload Length: 9, Type: HEADERS, Flags: 00000100, StreamId: 13, PayloadOffset: 0, DontUseMemPool: False, Payload: [BufferSegment Offset: 0 Count: 9 Data: [83, BE, C7, 87, C6, C5, C4, C3, C2]]]","stack":"  at Connections.HTTP2.HTTP2Handler.RunHandler () [0x00975]

{"tid":691,"div":"HTTP2Handler","msg":"New frame received: [HTTP2FrameHeaderAndPayload Length: 35, Type: HEADERS, Flags: 00000100, StreamId: 13, PayloadOffset: 0, DontUseMemPool: False, Payload: [BufferSegment Offset: 0 Count: 35 Data: [88, C6, 61, 1D, 46, 72, 69, 2C, 20, 33, 30, 20, 44, 65, 63, 20, 32, 30, 32, 32, 20, 31, 34, 3A, 31, 32, 3A, 35, 30, 20, 47, 4D, 54, C5, C0]]]","stack":"  at Connections.HTTP2.HTTP2Handler.ReadThread () [0x00063]

{"tid":690,"div":"HTTP2Stream","msg":"[13] Process - processing frame: [HTTP2FrameHeaderAndPayload Length: 35, Type: HEADERS, Flags: 00000100, StreamId: 13, PayloadOffset: 0, DontUseMemPool: False, Payload: [BufferSegment Offset: 0 Count: 35 Data: [88, C6, 61, 1D, 46, 72, 69, 2C, 20, 33, 30, 20, 44, 65, 63, 20, 32, 30, 32, 32, 20, 31, 34, 3A, 31, 32, 3A, 35, 30, 20, 47, 4D, 54, C5, C0]]]","stack":"  at Connections.HTTP2.HTTP2Stream.ProcessIncomingFrames (System.Collections.Generic.List`1[T] outgoingFrames) [0x00074]

{"tid":690,"div":"RequestEventHelper","msg":"Enqueue request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: TimingData, Name: Waiting (TTFB), Time: 30.12.2022 15:12:51]","stack":"  at Core.RequestEventHelper.EnqueueRequestEvent (Core.RequestEventInfo event) [0x00012] 

{"tid":690,"div":"HPACKEncoder","msg":"[13] Decode - IndexedHeader: [:status, 200]","stack":"  at Connections.HTTP2.HPACKEncoder.Decode (Connections.HTTP2.HTTP2Stream context, System.IO.Stream stream, System.Collections.Generic.List`1[T] to) [0x0003f]

{"tid":690,"div":"HPACKEncoder","msg":"[13] Decode - IndexedHeader: [content-type, application\/grpc]","stack":"  at Connections.HTTP2.HPACKEncoder.Decode (Connections.HTTP2.HTTP2Stream context, System.IO.Stream stream, System.Collections.Generic.List`1[T] to) [0x0003f]

{"tid":690,"div":"HPACKEncoder","msg":"[13] Decode - LiteralHeaderFieldWithIncrementalIndexing_IndexedName: [date, Fri, 30 Dec 2022 14:12:50 GMT]","stack":"  at Connections.HTTP2.HPACKEncoder.Decode (Connections.HTTP2.HTTP2Stream context, System.IO.Stream stream, System.Collections.Generic.List`1[T] to) [0x00171]

{"tid":1,"div":"RequestEventHelper","msg":"Processing request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: TimingData, Name: Waiting (TTFB), Time: 30.12.2022 15:12:51]","stack":"  at Core.RequestEventHelper.ProcessQueue () [0x0001f] 

{"tid":690,"div":"HPACKEncoder","msg":"[13] Decode - IndexedHeader: [server, Kestrel]","stack":"  at Connections.HTTP2.HPACKEncoder.Decode (Connections.HTTP2.HTTP2Stream context, System.IO.Stream stream, System.Collections.Generic.List`1[T] to) [0x0003f]

{"tid":690,"div":"HPACKEncoder","msg":"[13] Decode - IndexedHeader: [x-magiconion-streaminghub-version, 2]","stack":"  at Connections.HTTP2.HPACKEncoder.Decode (Connections.HTTP2.HTTP2Stream context, System.IO.Stream stream, System.Collections.Generic.List`1[T] to) [0x0003f]

{"tid":690,"div":"RequestEventHelper","msg":"Enqueue request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: TimingData, Name: Headers, Time: 30.12.2022 15:12:51]","stack":"  at Core.RequestEventHelper.EnqueueRequestEvent (Core.RequestEventInfo event) [0x00012] 

{"tid":690,"div":"RequestEventHelper","msg":"Enqueue request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: Headers]","stack":"  at Core.RequestEventHelper.EnqueueRequestEvent (Core.RequestEventInfo event) [0x00012]

{"tid":690,"div":"RequestEventHelper","msg":"Enqueue request event: [RequestEventInfo SourceRequest: https:\/\/localhost:5001\/IChatHub\/Connect, Event: StreamingData, DataLength: 9]","stack":"  at Core.RequestEventHelper.EnqueueRequestEvent (Core.RequestEventInfo event) [0x00012] 

{"tid":690,"div":"HTTPResponse","msg":"AddStreamedFragment buffer length: 9 UnprocessedFragments: 1","stack":"  at HTTPResponse.VerboseLogging (System.String str) [0x00012]

```

**Comment by FreshL4ma** [comment]
I found a fix for this issue. In StreamingHubClientBase.cs I simply commented out this part:
```
public async Task __ConnectAndSubscribeAsync(TReceiver receiver, CancellationToken cancellationToken)
{
    var syncContext = SynchronizationContext.Current; // capture SynchronizationContext.
    var callResult = callInvoker.AsyncDuplexStreamingCall<byte[], byte[]>(DuplexStreamingAsyncMethod, host, option);

    this.writer = callResult.RequestStream;
    this.reader = callResult.ResponseStream;
    this.receiver = receiver;

    // Establish StreamingHub connection between the client and the server.
    Metadata.Entry messageVersion = default;
    try
    {
        // The client can read the response headers before any StreamingHub's message.
        // MagicOnion.Server v4.0.x or before doesn't send any response headers. The client is incompatible with that versions.
        // NOTE: Grpc.Net:
        //           If the channel can not be connected, ResponseHeadersAsync will throw an exception.
        //       C-core:
        //           If the channel can not be connected, ResponseHeadersAsync will **return** an empty metadata.
        var headers = await callResult.ResponseHeadersAsync.ConfigureAwait(false);
        messageVersion = headers.FirstOrDefault(x => x.Key == StreamingHubVersionHeaderKey);

        cancellationToken.ThrowIfCancellationRequested();

        // Check message version of StreamingHub.
        if (messageVersion != null && messageVersion.Value != StreamingHubVersionHeaderValue)
        {
            throw new RpcException(new Status(StatusCode.Internal, $"The message version of StreamingHub mismatch between the client and the server. (ServerVersion={messageVersion?.Value}; Expected={StreamingHubVersionHeaderValue})"));
        }
    }
    catch (RpcException e)
    {
        throw new RpcException(e.Status, $"Failed to connect to StreamingHub '{DuplexStreamingAsyncMethod.ServiceName}'. ({e.Status})");
    }

//This throws an error
    /*
    var firstMoveNextTask = reader.MoveNext(CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, cts.Token).Token);
    if (firstMoveNextTask.IsFaulted || messageVersion == null)
    {
        // NOTE: Grpc.Net:
        //           If an error is returned from `StreamingHub.Connect` method on a server-side,
        //           ResponseStream.MoveNext synchronously returns a task that is `IsFaulted = true`.
        //           `ConnectAsync` method should throw an exception here immediately.
        //       C-core:
        //           `firstMoveNextTask` is incomplete task (`IsFaulted = false`) whether ResponseHeadersAsync is failed or not.
        //           If the channel is disconnected or the server returns an error (StatusCode != OK), awaiting the Task will throw an exception.
        await firstMoveNextTask.ConfigureAwait(false);

        // NOTE: C-core: If the execution reaches here, Connect method returns without any error (StatusCode = OK). but MessageVersion isn't provided from the server.
        throw new RpcException(new Status(StatusCode.Internal, $"The request started successfully (StatusCode = OK), but the StreamingHub client has failed to negotiate with the server."));
    }
    this.subscription = StartSubscribe(syncContext, firstMoveNextTask);
    */

    this.subscription = StartSubscribe(syncContext);
}
```
and rewrote the StartSubscribe-Method like so:
```
async Task StartSubscribe(SynchronizationContext syncContext)
{
    var reader = this.reader;
    try
    {
        while (await reader.MoveNext(cts.Token))
        {
            try
            {
                ConsumeData(syncContext, reader.Current);
            }
            catch (Exception ex)
            {
                const string msg = "An error occurred when consuming a received message, but the subscription is still alive.";
                // log post on main thread.
                if (syncContext != null)
                {
                    syncContext.Post(state => logger.Error((Exception)state, msg), ex);
                }
                else
                {
                    logger.Error(ex, msg);
                }
            }

        }
    }
    catch (Exception ex)
    {
        if (ex is OperationCanceledException)
        {
            return;
        }
        const string msg = "An error occurred while subscribing to messages.";
        // log post on main thread.
        if (syncContext != null)
        {
            syncContext.Post(state => logger.Error((Exception)state, msg), ex);
        }
        else
        {
            logger.Error(ex, msg);
        }
    }
    finally
    {
        try
        {
#if !UNITY_WEBGL
            // set syncContext before await
            // NOTE: If restore SynchronizationContext in WebGL environment, a continuation will not be executed inline and will be stuck.
            if (syncContext != null && SynchronizationContext.Current == null)
            {
                SynchronizationContext.SetSynchronizationContext(syncContext);
            }
#endif
            await DisposeAsyncCore(false).ConfigureAwait(false);
        }
        finally
        {
            waitForDisconnect.TrySetResult(null);
        }
    }
}
```
