### ISSUE TITLE
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. MessagePackSerializationException: Failed to deserialize System.Int32 value.

### ISSUE THREAD

**Issue by rayshow9527** [Cysharp/MagicOnion#664]
I'm trying to return a model in response but get below exception, can someone help look into this issue?

server side code:
```
public async UnaryResult<TestModel> TestFunctionAsync(TestModel a)
        {
            var response = new TestModel()
            {
                X = a.X,
                Y = a.Y
            };

            return response;
        }
```
```
    [MessagePackObject]
    public class TestModel
    {
        [Key(0)]
        public int X { get; set; }
        [Key(1)]
        public int Y { get; set; }
    }
```

client side code:
```
        public async Task<ActionResult> TestAsync()
        {


            var channel = GrpcChannel.ForAddress("https://localhost:5001");

            // Create a proxy to call the server transparently.
            var client = MagicOnionClient.Create<IMyFirstService>(channel);

            // Call the server-side method using the proxy.
            var result = await client .TestFunctionAsync(new TestModel()
            {
                X = 123,
                Y = 234
            });

            
            Console.WriteLine($"Result: {result}");

            return Ok(true);
        }
```

Exception message:
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. MessagePackSerializationException: Failed to deserialize System.Int32 value. MessagePackSerializationException: Unexpected msgpack code 146 (fixarray) encountered.", DebugException="MessagePack.MessagePackSerializationException: Failed to deserialize System.Int32 value.
 ---> MessagePack.MessagePackSerializationException: Unexpected msgpack code 146 (fixarray) encountered.
   at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.ReadInt32()
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](ReadOnlySequence`1& byteSequence, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at MagicOnion.Serialization.MessagePackMagicOnionSerializerProvider.MessagePackMagicOnionSerializer.MagicOnion.Serialization.IMagicOnionSerializer.Deserialize[T](ReadOnlySequence`1& bytes)
   at MagicOnion.GrpcMethodHelper.<>c__DisplayClass9_0`1.<CreateBoxedMarshaller>b__1(DeserializationContext ctx)
   at Grpc.Net.Client.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at MagicOnion.Client.ResponseContextRaw`2.FromRawResponseToResponseAsync()
   at MagicOnion.UnaryResult`1.UnwrapResponse()
   at BenchmarkWebClientTest.Controllers.BenchmarkController.TestLog() in C:\SourceCode\others\MagicOnionClientTest\BenchmarkWebClientTest\Controllers\BenchmarkController.cs:line 76
   at lambda_method5(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by mayuki** [comment]
We were unable to reproduce this issue. It's possible that the type definition may differ between the client and server.
