### ISSUE TITLE
How to correctly handle cancellation token?

### ISSUE THREAD

**Issue by MkazemAkhgary** [Cysharp/MagicOnion#86]
If I want to cancel server stream from client, How do i handle cancellation in server side correctly?

client call

```c#
await client.WithCancellationToken(token).ServerStreamTest();
```

In server we have

```c#
timer.Elapsed += async e =>
{
    await stream.WriteAsync(ResponseFrom(e));
};
```

Obviously this handler should be detached before stream is disposed. this will cause exception in server side. How do i know that cancellation is requested?

If I detach the handler in finally block (not sure if that's thread safe), Handler is detached but I still get the following exception

```
W0128 12:01:35.898550 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCallServer.cs:line 137
   at Grpc.Core.Internal.DuplexStreamingServerCallHandler`2.HandleCall(ServerRpcNew newRpc, CompletionQueueSafeHandle cq) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\ServerCallHandler.cs:line 271
   at Grpc.Core.Server.HandleCallAsync(ServerRpcNew newRpc, CompletionQueueSafeHandle cq, Action continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\Server.cs:line 346
```

Previously I made a duplex stream so client would send cancellation request and server would close stream correctly. but I was wondering if i can use `WithCancellationToken` provided by framework it self?

**Comment by neuecc** [comment]
If you use `StreamingHub`, you can use `StreamingHubClient.DisposeAsync` in client and can reveice  `StreamingHubBase.OnDisconnected` on server.
If you use raw gRPC APIs(ServiceBase + DuplexStreamingResult), follows gRPC C# manner.
