### ISSUE TITLE
Error while generating code with moc.exe

### ISSUE THREAD

**Issue by vova-lantsov-dev** [Cysharp/MagicOnion#98]
```
$ ./moc.exe -i "D:\Projects\Study\Unity_2D_Test_1\Assembly-CSharp.csproj" -o "D:\Projects\Study\Unity_2D_Test_1"
Project Compilation Start:D:\Projects\Study\Unity_2D_Test_1\Assembly-CSharp.csproj
Project Compilation Complete:00:00:13.1413338

Method Collect Start

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MagicOnion.CodeAnalysis.MethodCollector.ExtractRequestResponseType(IMethodSymbol method, MethodType& methodType, String& requestType, String& responseType, ITypeSymbol& unwrappedOriginalResponseType) in C:\Git\MagicOnion\src\MagicOnion.UniversalCodeGenerator\CodeAnalysis\MethodCollector.cs:line 203
   at MagicOnion.CodeAnalysis.MethodCollector.CreateMethodDefinition(IMethodSymbol y) in C:\Git\MagicOnion\src\MagicOnion.UniversalCodeGenerator\CodeAnalysis\MethodCollector.cs:line 165
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MagicOnion.CodeAnalysis.MethodCollector.<CollectServiceInterface>b__7_0(INamedTypeSymbol x) in C:\Git\MagicOnion\src\MagicOnion.UniversalCodeGenerator\CodeAnalysis\MethodCollector.cs:line 94
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MagicOnion.CodeGenerator.Program.Main(String[] args) in C:\Git\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Program.cs:line 88
Segmentation fault
```

**Comment by vova-lantsov-dev** [comment]
Unity_2D_Test_1 here is Unity project's root.

**Comment by neuecc** [comment]
thanks you for report, please show target interface code?

**Comment by vova-lantsov-dev** [comment]
@neuecc 
```
using System.Collections.Generic;
using System.Threading.Tasks;
using MagicOnion;
using MessagePack;

public interface IRatingHubReceiver
{
    void OnScoreChanged(List<Player> newScores);
}
 
public interface IRatingHub : IStreamingHub<IRatingHub, IRatingHubReceiver>
{
    Task<Player> JoinAsync(string id);

    Task<List<Player>> GetScoresAsync();
        
    Task<List<Player>> SetScoreAsync(int score);
}

public sealed class RatingReceiver : IRatingHubReceiver
{
    private List<Player> _players;

    public RatingReceiver(List<Player> players)
    {
        _players = players;
    }

    public void OnScoreChanged(List<Player> newScores)
    {
        if (newScores == null || newScores.Count > 5)
            return;

        lock (_players)
            _players = newScores;
    }
}

[MessagePackObject]
public sealed class Player
{
    [Key(0)]
    public string Id { get; set; }
    
    [Key(1)]
    public int Score { get; set; }
}
```
